# cmake/UpdateVersion.cmake
# Invoked as a pre-build step each cmake --build run.
# Reads build_number.txt, increments it, then writes
# ${BINARY_DIR}/generated/version.h so main.cpp picks up the new value.

set(BUILD_NUMBER_FILE "${SOURCE_DIR}/build_number.txt")

if(EXISTS "${BUILD_NUMBER_FILE}")
    file(READ "${BUILD_NUMBER_FILE}" BUILD_NUMBER)
    string(STRIP "${BUILD_NUMBER}" BUILD_NUMBER)
else()
    set(BUILD_NUMBER 0)
endif()

math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
file(WRITE "${BUILD_NUMBER_FILE}" "${BUILD_NUMBER}")

file(MAKE_DIRECTORY "${BINARY_DIR}/generated")
file(WRITE "${BINARY_DIR}/generated/version.h"
"#pragma once
// Auto-generated by cmake/UpdateVersion.cmake — do not edit
#define MZSPECIALS_VERSION_MAJOR ${VERSION_MAJOR}
#define MZSPECIALS_VERSION_MINOR ${VERSION_MINOR}
#define MZSPECIALS_VERSION_PATCH ${BUILD_NUMBER}
#define MZSPECIALS_VERSION \"${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_NUMBER}\"
")

message(STATUS "mzSpecials version: ${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_NUMBER}")
